image: node:7.4.0

stages:
- setup
- test
- build
- deploy

build:
  stage: build
  script:
    - npm install -g bower grunt-cli protractor s3-deploy
    - npm install
    - bower install --allow-root --force-latest
    - grunt test
    - grunt build
    - s3-deploy './dist/**' --cwd './dist/' --gzip --region $AWS_REGION --bucket $AWS_BUCKET
  only:
    - master
