image: node:7.10.0

stages:
  - setup
  - test
  - build
  - deploy
build:
  stage: build
  script:
    - rm -irf node_modules/
    - npm install -g s3-deploy
    - npm install
    - npm run generate-test
    - s3-deploy './dist/**' --etag --cache 31536000 --cwd './dist/' --gzip --region $AWS_REGION --bucket $AWS_BUCKET_TEST2
  only:
    - etereo-next
